sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t eoatley/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eoatley/docker-react npm run test